services:
  oracle:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle_container
    environment:
      ORACLE_PASSWORD: mypassword
      APP_USER: myuser
      APP_USER_PASSWORD: mypassword
    ports:
      - "1522:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  springboot-app:
    build: .
    container_name: springboot_container
    ports:
      - "8080:8080"
    depends_on:
      oracle:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.OracleDialect